name: dressifyai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_dotenv: ^6.0.0
  flutter_floating_bottom_bar: ^1.4.0
  google_fonts: ^8.0.2
  google_sign_in: ^7.2.0
  iconsax: ^0.0.8
  provider: ^6.1.5+1
  shimmer: ^3.0.0
  sqflite: ^2.4.1
  supabase_flutter: ^2.12.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
